apiVersion: v1
kind: Namespace
metadata:
  name: dev-deps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: dev-deps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      enableServiceLinks: false
      containers:
      - name: postgres
        image: supabase/postgres:15.14.1.021
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_USER
          value: "supabase_admin"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: dev-deps
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
